import './globals.css'
import "./tailwind.css";
import { Inter } from 'next/font/google';
const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const inter = Inter({ subsets: ['latin'] })
import { SessionProvider } from 'next-auth/react';
import GithubSessionProvider from '@/providers/SessionProvider';
export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang="en">
      <GithubSessionProvider>
      <body className={inter.className}>{children}</body>
      </GithubSessionProvider>
    </html>

  )
}
